### ISSUE TITLE
Indexing and search

### ISSUE THREAD

**Issue by joshkopecek** [rusty1s/mongoose-i18n-localize#2]
What about indexing? If I have a model

``` javascript
var schema = new mongoose.Schema({
    name: {
        type: String,
        i18n: true
    }
});
```

How can I do cross-language search? Or will it always have to be `schema.find({'name.en': /search/})`?

**Comment by rusty1s** [comment]
This module just replaces the values with `i18n: true` with an object that contains the values of all defined languages, so cross-language searches are not directly supported. You should check the mongoose api to find what you are looking for.

**Comment by joshkopecek** [comment]
Yeah, already looked into this quite deeply. It seems when you have a dynamic key for an object there's no way to do a search across all keys (something like `{'name.*': /searchstring/}`), unless you declare them in advance and enumerate the individual keys. Then you end up with a million `$or`s and huge objects with redundant keys.

That also means for my app I would have to declare all potential languages.

This was also a problem when I was working with MySQL, where you could serialize a string, but then it removed the possibility of indexing it properly.

**Comment by rusty1s** [comment]
You need to declare all potentials languages anyway, so the best option would be to write a wrapper that does what you describe above.

**Comment by joshkopecek** [comment]
Thanks. Still not finalised exactly how I'm going to do this with a search facility unless search on the client end is done using separate languages.

**Comment by jfmmm** [comment]
How did you made that work? Even if I specify each language in the index it won't work.

```javascript
posts.index({
  'title.fr': 'text',
  'title.en': 'text'
});
```

edit: or you went with the manual regex way? That seem to work but it's not pretty and won't work well with french special character.
