### ISSUE TITLE
Support for arrays of strings

### ISSUE THREAD

**Issue by lardois** [rusty1s/mongoose-i18n-localize#4]
Hi,
would it be hard to implement support for arrays of strings? Like:
`  name: {
    type: String,
  },
  localizedName: {
    type: String,
    i18n: true,
  },
  nicknames: {
    type: [String],
    i18n: true,
  }`

So that as a result you would have
name
localizedName.fi
and also
nicknames.fi[0]?

**Comment by lardois** [comment]
Figured this one out.. maybe pull request if anybody other finds this interesting enough?

**Comment by rusty1s** [comment]
Pull request is welcome 👍
